name: CI/CD Bot

on:
  push:
    branches: [master]

jobs:
  deploy-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Pull FakkaBot@latest on server
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PORT: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull

      - name: Download dependencies
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PORT: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            npm install

      - name: Build production
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PORT: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            npm run build

      - name: Restart session
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PORT: ${{ secrets.PORT }}
          script: |
            pm2 restart fakkabot
